# Generated by Django 4.0 on 2022-01-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_studentacademics_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Roll_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
